# Generated by Django 4.2.4 on 2023-10-13 04:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'gif', 'png'])])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100)),
                ('sent_to', models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], max_length=150)),
                ('institution', models.CharField(max_length=100)),
                ('date_sent', models.DateField()),
                ('office_from', models.CharField(choices=[('Office of The Governor', 'Office of The Governor'), ('Office_of_The_Deputy_Governor', 'Office of The Deputy Governor')], max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='files/Sent/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('remarks', models.TextField(blank=True, max_length=100, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fms.profile')),
            ],
            options={
                'verbose_name': 'Sent',
                'verbose_name_plural': 'Sent',
                'ordering': ['-date_sent'],
            },
        ),
        migrations.CreateModel(
            name='Received',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100)),
                ('entity', models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('office_to', models.CharField(choices=[('Office of The Governor', 'Office of The Governor'), ('Office of The Deputy Governor', 'Office of The Deputy Governor')], max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='files/Received/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('remarks', models.TextField(blank=True, max_length=100, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fms.profile')),
            ],
            options={
                'verbose_name': 'Received',
                'verbose_name_plural': 'Received',
                'ordering': ['-date_received'],
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_token', models.PositiveIntegerField()),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
